---
params:
  inc:
    # Blog Information
      # Set a shortname to enable disqus comments
#      shortname:  false
    
    # Sharing settings
    sharing:
      twitter:    false
      facebook:   false
      gplus:      false
      hn:         false
      
    
   # Analytics     
    analytics:
#      googleid: UA-00000000-0
#      piwik:
#        domain: piwik.example.com
#        siteid: 0
        
    # Google Fonts
    # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
    google_font: 'Droid+Sans:400,700'
    
    # Setup your fonts, colors etc at _assets/stylesheets/main.scss
